name: CI

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 #busca o código mais atual dentro do repositório do github
      
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install Dependencies
        run: sudo yarn        
      - name: Build
        run: sudo yarn build

      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules, !ormconfig.json, !docker-compose.yml"
          target: "~/rentalx"
           
      - name: Update_API
        uses: appleboy/ssh-action@v1.0.0  
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ~/rentalx
            yarn install
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentalx
            
          
